### ISSUE TITLE
Bug: fetch block data error with axon testnet

### ISSUE THREAD

**Issue by Naupio** [Magickbase/axon_explorer#10]
fetch block data with error:

```
axon_explorer    | 2022-05-19T08:10:44.166 application=indexer fetcher=block_catchup first_block_number=5162 last_block_number=5153 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.elixir_to_params/1
axon_explorer    |     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/transaction.ex:116: EthereumJSONRPC.Transaction.elixir_to_params(%{nil: nil})
axon_explorer    |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
axon_explorer    |     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:50: EthereumJSONRPC.Blocks.from_responses/2
axon_explorer    |     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:484: EthereumJSONRPC.fetch_blocks_by_params/3
axon_explorer    |     (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
axon_explorer    |     (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:205: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
axon_explorer    |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
axon_explorer    |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
```

**Comment by Naupio** [comment]
error message
```axon_explorer    | 2022-05-20T02:43:27.786 application=indexer fetcher=block_catchup first_block_number=22536 last_block_number=22527 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.elixir_to_params/1
axon_explorer    |     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/transaction.ex:116: EthereumJSONRPC.Transaction.elixir_to_params(%{nil: nil})
axon_explorer    |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
axon_explorer    |     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:50: EthereumJSONRPC.Blocks.from_responses/2
axon_explorer    |     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:484: EthereumJSONRPC.fetch_blocks_by_params/3
axon_explorer    |     (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
axon_explorer    |     (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:205: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
axon_explorer    |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
axon_explorer    |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4```

**Comment by Naupio** [comment]
seems transaction rpc data incompatible 
```
iex(axon_explorer@127.0.0.1)5> EthereumJSONRPC.fetch_blocks_by_range(1..1, json_rpc_named_arguments)
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.elixir_to_params/1    
    
    The following arguments were given to EthereumJSONRPC.Transaction.elixir_to_params/1:
    
        # 1
        %{nil: nil}
    
    Attempted function clauses (showing 3 out of 3):
    
        def elixir_to_params(-%{
      "blockHash" => block_hash,
      "blockNumber" => block_number,
      "from" => from_address_hash,
      "gas" => gas,
      "gasPrice" => gas_price,
      "hash" => hash,
      "input" => input,
      "nonce" => nonce,
      "r" => r,
      "s" => s,
      "to" => to_address_hash,
      "transactionIndex" => index,
      "v" => v,
      "value" => value,
      "type" => type,
      "maxPriorityFeePerGas" => max_priority_fee_per_gas,
      "maxFeePerGas" => max_fee_per_gas
    } = transaction-)
```

**Comment by Keith-CY** [comment]
It looks like a block includes a `nil`, which may be a failed transaction. Can you post the actual data returned from the node?

**Comment by Naupio** [comment]
expect like this:
```
      ...>   %{
      ...>     "blockHash" => "0xe52d77084cab13a4e724162bcd8c6028e5ecfaa04d091ee476e96b9958ed6b47",
      ...>     "blockNumber" => "0x22",
      ...>     "chainId" => "0x4d",
      ...>     "condition" => nil,
      ...>     "creates" => "0xffc87239eb0267bc3ca2cd51d12fbf278e02ccb4",
      ...>     "from" => "0xe8ddc5c7a2d2f0d7a9798459c0104fdf5e987aca",
      ...>     "gas" => "0x47b760",
      ...>     "gasPrice" => "0x174876e800",
      ...>     "hash" => "0x3a3eb134e6792ce9403ea4188e5e79693de9e4c94e499db132be086400da79e6",
      ...>     "input" => "0x6060604052341561000f57600080fd5b336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506102db8061005e6000396000f300606060405260043610610062576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630900f01014610067578063445df0ac146100a05780638da5cb5b146100c9578063fdacd5761461011e575b600080fd5b341561007257600080fd5b61009e600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610141565b005b34156100ab57600080fd5b6100b3610224565b6040518082815260200191505060405180910390f35b34156100d457600080fd5b6100dc61022a565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b341561012957600080fd5b61013f600480803590602001909190505061024f565b005b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415610220578190508073ffffffffffffffffffffffffffffffffffffffff1663fdacd5766001546040518263ffffffff167c010000000000000000000000000000000000000000000000000000000002815260040180828152602001915050600060405180830381600087803b151561020b57600080fd5b6102c65a03f1151561021c57600080fd5b5050505b5050565b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614156102ac57806001819055505b505600a165627a7a72305820a9c628775efbfbc17477a472413c01ee9b33881f550c59d21bee9928835c854b0029",
      ...>     "nonce" => "0x0",
      ...>     "publicKey" => "0xe5d196ad4ceada719d9e592f7166d0c75700f6eab2e3c3de34ba751ea786527cb3f6eb96ad9fdfdb9989ff572df50f1c42ef800af9c5207a38b929aff969b5c9",
      ...>     "r" => "0xad3733df250c87556335ffe46c23e34dbaffde93097ef92f52c88632a40f0c75",
      ...>     "raw" => "0xf9038d8085174876e8008347b7608080b903396060604052341561000f57600080fd5b336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506102db8061005e6000396000f300606060405260043610610062576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630900f01014610067578063445df0ac146100a05780638da5cb5b146100c9578063fdacd5761461011e575b600080fd5b341561007257600080fd5b61009e600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610141565b005b34156100ab57600080fd5b6100b3610224565b6040518082815260200191505060405180910390f35b34156100d457600080fd5b6100dc61022a565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b341561012957600080fd5b61013f600480803590602001909190505061024f565b005b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415610220578190508073ffffffffffffffffffffffffffffffffffffffff1663fdacd5766001546040518263ffffffff167c010000000000000000000000000000000000000000000000000000000002815260040180828152602001915050600060405180830381600087803b151561020b57600080fd5b6102c65a03f1151561021c57600080fd5b5050505b5050565b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614156102ac57806001819055505b505600a165627a7a72305820a9c628775efbfbc17477a472413c01ee9b33881f550c59d21bee9928835c854b002981bda0ad3733df250c87556335ffe46c23e34dbaffde93097ef92f52c88632a40f0c75a072caddc0371451a58de2ca6ab64e0f586ccdb9465ff54e1c82564940e89291e3",
      ...>     "s" => "0x72caddc0371451a58de2ca6ab64e0f586ccdb9465ff54e1c82564940e89291e3",
      ...>     "standardV" => "0x0",
      ...>     "to" => nil,
      ...>     "transactionIndex" => "0x0",
      ...>     "v" => "0xbd",
      ...>     "value" => "0x0"
      ...>   }
```

**Comment by Naupio** [comment]
expect transaction object  like this:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/12268276/169510552-6198287b-179c-4fd1-bba8-22d0a59260af.png">

link https://eth.wiki/json-rpc/API

**Comment by Naupio** [comment]
but now axon eth_getBlockByNumber api return block object with transcations file like this:
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/12268276/169511322-3374d698-f4ae-4459-85f4-e9e1047d4521.png">

**Comment by Keith-CY** [comment]
> transactions return like this
> 
> ```
> axon_explorer    |     "transactions" => [
> axon_explorer    |       %{
> axon_explorer    |         "public" => "0xe9114cf964bdaa1a7a0d9f0364964f7cc1ce4c6b134a4eda5b210914317c81de4aa0df9f9ca6324e8d2a0105725c5ee743496663e7a9e8c4b0e1ee4a36053d66",
> axon_explorer    |         "sender" => "0x7cc8b5bd4b350cd8380769d41ef763012d53a9b2",
> axon_explorer    |         "transaction" => %{
> axon_explorer    |           "chain_id" => 5,
> axon_explorer    |           "hash" => "0x9914c3862f142a63f5c19aa74d34ec75352ac3bc4495065ccd69e3e6265d7d51",
> axon_explorer    |           "signature" => %{
> axon_explorer    |             "r" => [218, 49, 133, 239, 172, 49, 196, 47, 167, 13, 208, 126, 235,
> axon_explorer    |              31, 96, 33, 129, 38, 213, ...],
> axon_explorer    |             "s" => [29, 15, 229, 33, 66, 118, 36, 200, 19, 250, 254, 58, 245,
> axon_explorer    |              27, 193, 222, 38, 223, ...],
> axon_explorer    |             "standard_v" => 1
> axon_explorer    |           },
> axon_explorer    |           "unsigned" => %{
> axon_explorer    |             "access_list" => [],
> axon_explorer    |             "action" => %{
> axon_explorer    |               "Call" => "0x5cf83df52a32165a7f392168ac009b168c9e8915"
> axon_explorer    |             },
> axon_explorer    |             "data" => [],
> axon_explorer    |             "gas_limit" => "0x5208",
> axon_explorer    |             "gas_price" => "0x3",
> axon_explorer    |             "max_priority_fee_per_gas" => "0x3",
> axon_explorer    |             "nonce" => "0x189c1",
> axon_explorer    |             "value" => "0x1"
> axon_explorer    |           }
> axon_explorer    |         }
> axon_explorer    |       },
> ```

Transaction(0x9914c3862f142a63f5c19aa74d34ec75352ac3bc4495065ccd69e3e6265d7d51) mentioned in this data is not found on chain, that's why `nil` was passed into `EthereumJSONRPC.Transaction.elixir_to_params`

**Comment by Keith-CY** [comment]
Will be fixed by https://github.com/nervosnetwork/axon/pull/374

**Comment by Keith-CY** [comment]
> seems not fixed yet
> 
> i find the official rpc doc here: [playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/execution-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/execution-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false)
> 
> the transcations field of block object will return like this:
> 
> ![image](https://user-images.githubusercontent.com/12268276/169839548-239da4d8-ee07-4592-aea1-733ef52d52fc.png)

Transactions in response of `eth_getBlockByNumber` with `hydrated transaction: true` is not following the standard

```
{
	"jsonrpc": "2.0",
	"result": {
		"hash": "0xe2fa63ac0f0424f6e02958c06cbcf2d1883994a7c8ae4260095d09fef6d31b08",
		"parentHash": "0x61c2ee6e68e31d5c8ad80354b379740b99d56ce38c88bb4026769d96bae2428c",
		"sha3Uncles": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"author": "0xf4cc1652dcec2e5de9ce6fb1b6f9fa9456e957f1",
		"miner": "0xf4cc1652dcec2e5de9ce6fb1b6f9fa9456e957f1",
		"stateRoot": "0x579abee3530f9ce3f52bbb5574a56b6a233e599bb1b4681cffa50b856f79f0d1",
		"transactionsRoot": "0x63fa6c9126e9f2a820a4fde08cb178153c8740a4ca9508559f823aff874ec732",
		"receiptsRoot": "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
		"number": "0x4",
		"gasUsed": "0x112f1a",
		"gasLimit": "0x1c9c380",
		"extraData": "0x",
		"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
		"timestamp": "0x628ba5b5",
		"difficulty": "0x1",
		"totalDifficulty": null,
		"sealFields": [],
		"baseFeePerGas": "0x539",
		"uncles": [],
		"transactions": [
			{
				"transaction": {
					"unsigned": {
						"nonce": "0x5",
						"max_priority_fee_per_gas": "0x9502f900",
						"gas_price": "0x95030372",
						"gas_limit": "0x1e8480",
						"action": "Create",
						"value": "0x0",
						"data": [...],
						"access_list": []
					},
					"signature": {
						"r": [...],
						"s": [...],
						"standard_v": 0
					},
					"chain_id": 5,
					"hash": "0x63fa6c9126e9f2a820a4fde08cb178153c8740a4ca9508559f823aff874ec732"
				},
				"sender": "0x8ab0cf264df99d83525e9e11c7e4db01558ae1b1",
				"public": "0x1ddc35212b7fc7ff6685b17d91f77c972535aee5c7ae5684d3e72b986f08834bb6d9f0d2aadc50716cea7b59d5eadfc9366e348ed596b924f4e746247b673c57"
			}
		],
		"size": "0x289",
		"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"nonce": "0x0"
	},
	"id": 1
}
```

**Comment by Naupio** [comment]
new issue link #15
